/*---------------------------------------------------------------------------*
 *  gsl.d - LIBERO dialog data definitions for gsl.c.                        *
 *  Generated by LIBERO 2.4 on 11 Oct, 2010, 17:16.                          *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define error_event                     0
#define fatal_event                     1
#define message_event                   2
#define ok_event                        3
#define shutdown_event                  4
#define _LR_STATE_after_init            0


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE display_error_message        (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [1][5] =
{
    { 0,0,0,0,0 }
};

static word _LR_action [1][5] =
{
    { 2,2,2,1,3 }
};

#if (defined (SMT_PROFILE))
static word _LR_count [2];
static long _LR_time  [2];
static word _LR_flow  [1][5];
#endif

static word _LR_offset [] =
{
    0,
    0,
    1,
    3
};

static word _LR_vector [] =
{
    _LR_STOP,
    0,_LR_STOP,
    1,_LR_STOP
};

static HOOK *_LR_module [2] = {
    display_error_message,
    terminate_the_thread
};

#if (defined (DEBUG))
static char *_LR_mname [2] =
{
     "Display-Error-Message",
     "Terminate-The-Thread"
};

static char *_LR_sname [1] =
{
     "After-Init"
};

static char *_LR_ename [5] =
{
     "Error-Event",
     "Fatal-Event",
     "Message-Event",
     "Ok-Event",
     "Shutdown-Event"
};
#else
static char *_LR_mname [2] =
{
     "0",
     "1"
};

static char *_LR_sname [1] =
{
     "0"
};

static char *_LR_ename [5] =
{
     "0",
     "1",
     "2",
     "3",
     "4"
};
#endif
